spring.datasource.url=jdbc:mysql://localhost:3308/podproducerdb
spring.datasource.username=myuser
spring.datasource.password=mypassword
#spring.jpa.hibernate.ddl-auto=update

podcastExists.api.url=http://localhost:8081/pods/podcasts/podcasts/{id}/exists
podcastAssociated.api.url=http://localhost:8081/pods/podcasts/podcasts/{podcastid}/producerassociated/{producerid}
