spring.datasource.url=jdbc:mysql://localhost:3308/podproducerdb
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.jpa.hibernate.ddl-auto=create-drop

podcastExists.api.url=
podcastAssociated.api.url=
